owner: fcg3232
repo: SDStatus

# Monitors (5-minute checks by default)
sites:
  # PRODUCTION (naked domains)
  - name: Admin (Prod)
    url: https://admin.secondarydao.com
  - name: App (Prod)
    url: https://app.secondarydao.com
  - name: API (Prod)
    url: https://api.secondarydao.com/health
  - name: Rent (Prod)
    url: https://rent.secondarydao.com
  - name: Explorer (Prod)
    url: https://explorer.secondarydao.com

  # DEVELOPMENT (test.* domains)
  - name: Admin (Dev)
    url: https://test.admin.secondarydao.com
  - name: App (Dev)
    url: https://test.app.secondarydao.com
  - name: API (Dev)
    url: https://testapi.secondarydao.com/health
  - name: Rent (Dev)
    url: https://test.rent.secondarydao.com
  - name: Explorer (Dev)
    url: https://test.explorer.secondarydao.com

status-website:
  cname: status.secondarydao.com
  name: SecondaryDAO Status
  introTitle: Live Service Monitoring
  introMessage: >
    SecondaryDAO SA de CV • Real-time monitoring of all production and development services.
    Checks run every 5 minutes via GitHub Actions.
  theme: dark
  navbar:
    - title: Home
      href: https://secondarydao.com
    - title: App
      href: https://app.secondarydao.com
    - title: Docs
      href: https://docs.secondarydao.com
